source: ./source
destination: ./_site
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true
encoding: UTF-8
#exclude: ["node_modules"]
#do not commit this exclude part
#exclude:
#  - '_posts'
#  - 'guide' 
#  - 'author_generator'
#end - do not commit this exclude part
paginate: 10
paginate_path: "blog/page:num"
description: Cloudify is an open source application and network orchestration framework based on TOSCA that supports hybrid cloud deployments bridging public and private environments.

latest_cloudify_version: 3.4

gems:
  - jekyll-seo-tag
 
#Manage Download files:
#-----------------------Change this when new version is up---------------------#
Repo_url: http://repository.cloudifysource.org/cloudify/4.0.1/sp-release/
CM_Repo_url: http://repository.cloudifysource.org/cloudify/17.3.31/release/
Centos_ent_cli: cloudify-4.0.1~sp.el6.x86_64.rpm
Debian_ent_cli: cloudify_4.0.1~sp_amd64.deb
Windows_ent_cli: cloudify-windows-cli_4.0.1-sp.exe
Centos_cm_cli: cloudify-17.3.31~community.el6.x86_64.rpm
Debian_cm_cli: cloudify_17.3.31~community_amd64.deb
Windows_cm_cli: cloudify-windows-cli_17.3.31-community.exe
Premium_qcow: cloudify-manager-premium-4.0.1.qcow2
Composer_version: 2.3
Cloudify_version: 4.0.1
Docs_version: 4.0.0
Short_version: 4.0.1
aws_plugin_version: 1.4.11
vcloud_plugin_version: 1.3.1
vsphere_plugin_version: 2.3.0
openstack_plugin_version: 2.0.1
kubernetes_plugin_version: 1.0.0
fabric_plugin_version: 1.4.2
diamond_plugin_version: 1.3.5
docker_plugin_version: 1.3.2
psutil_plugin_version: 1.0.2
hostpool_plugin_version: 1.4
gcp_plugin_version: 1.0
azure_plugin_version: 1.4.1
Release_version: 3.4.2~sp-420
Release: 420
cfy_current_release: 4.0
cfy_next_release: 4.1