source: ./source
destination: ./_site
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: true
encoding: UTF-8
#exclude: ["node_modules"]
#do not commit this exclude part
#exclude:
#  - '_posts'
#  - 'guide' 
#  - 'author_generator'
#end - do not commit this exclude part
paginate: 5
paginate_path: "blog/page:num"

latest_cloudify_version: 3.4

gems:
  - jekyll-seo-tag

#Manage Download files:
#-----------------------Change this when new version is up---------------------#
Release_version: 3.4.0~1-401
Cloudify_version: 3.4.0.1
Docs_version: 3.4.1
Short_version: 3.4
Release: 401